[package]
name = "ui"
version = "0.1.0"
authors = ["root"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew.git", branch = "master" }
serde = "1"
serde_derive = "1"
serde_json = "1.0.26"
failure = "0.1"
wdview_msg = { path = "../wdview_msg" }
stdweb = "0.4"