[package]
name = "server"
version = "0.1.0"
authors = ["root"]

[dependencies]
failure = "0.1"
tungstenite = "0.5.2"
yew = { git = "https://github.com/DenisKolodin/yew.git", branch = "master" }
ui = { path = "../ui" }